In [1]:
#!pip install dash_bootstrap_components

In [2]:
import os

In [3]:
cwd = os.getcwd()

In [4]:
import dash
from dash import dcc
from dash import html
from dash import callback_context
from dash import dash_table

import plotly.graph_objects as go
from plotly.subplots import make_subplots

from dash import Dash, Input, Output, callback, State

from jupyter_dash import JupyterDash

import dash_bootstrap_components as dbc

In [5]:
PAGES_STYLE = "pagesstyles.css"
CONTENT_STYLES = "content.css"
external_stylesheets=[dbc.themes.BOOTSTRAP, PAGES_STYLE, CONTENT_STYLES]

app = JupyterDash(__name__,requests_pathname_prefix="/dash1/",routes_pathname_prefix='/dash1/',
                  external_stylesheets=external_stylesheets,
                  meta_tags=[{'name': 'viewport', 'content': 'width=device-width, initial-scale=1'}],
                 suppress_callback_exceptions=True)
# Create server variable with Flask server object for use with gunicorn
server = app.server

In [6]:
import pandas as pd

# Color Code

In [7]:
import plotly.graph_objects as go
import plotly.express as px
from itertools import cycle

# colors
palette = cycle(px.colors.qualitative.Bold)
#palette = cycle(['black', 'grey', 'red', 'blue'])

In [8]:
from dashboard_libraries import all_data_tables as adt
dashdataandtables = adt.DashDataAndTables()

style_table={
                #'maxHeight': '50ex',
                'height': '44vh', ## does not know any detail about parent container
                'overflowY': 'scroll', # 'auto'
                'width': '100%',
                'minWidth': '100%',
            }

# style cell
style_cell={
    'fontFamily': 'Open Sans',
    'textAlign': 'center',
    #'height': '60px',
    #'padding': '2px 22px',
    ##'height': '11px', ### this did not have any impact, see css in DataTable Definition
    'padding': '0px 0px',
    'whiteSpace': 'inherit',
    #'overflow': 'hidden',
    #'textOverflow': 'ellipsis',
    "padding-left": 0,
     "padding-right":0,
     "margin-left":0,
     "margin-right": 0,
     "fontSize":10,
}

In [9]:
dashdataandtables.limits_table_df.set_index('id', inplace=True, drop=False)
dashdataandtables.limits_table_df['expid'] = dashdataandtables.limits_table_df['id'] 
dashdataandtables.limits_table_df

,rowid,id,spin_dependency,experiment,official,greatest_hit,data_label,result_type,data_reference,year,expid
id,,,,,,,,,,,
1193,0,1193,SD,Experiment DMTOOL,1,0,dmtool,Th,dmtool,2023,1193
1194,1,1194,SD,Experiment D,1,0,d,Th,d,2023,1194
1195,2,1195,SD,Experiment M,1,0,m,Th,m,2020,1195
1196,3,1196,SD,Experiment T,1,0,t,Th,t,2020,1196
1197,4,1197,SD,Experiment O,1,0,o,Th,o,2020,1197
1198,5,1198,SD,Experiment L,1,0,l,Th,l,2020,1198

In [10]:
filter_df = [
            {'variable': 'year', 'label': '2020', 'value': '2020', 'data_type':'number'},
            {'variable': 'year', 'label': '2001', 'value': '2001', 'data_type':'number'}]

In [11]:
def FilterLimits(filter_df_in):
    all_limits = dashdataandtables.limits_table_df.copy()
    all_exp = []
    for r in range(0,len(filter_df)):
        #print(filter_df_in[r-1]['variable'])
        #print(filter_df_in[r-1]['value'])
        if filter_df_in[r-1]['data_type'] == 'number':
            filter_value = int(filter_df_in[r-1]['value'])
        else:
            filter_value = filter_df_in[r-1]['value']
        condition = all_limits[filter_df_in[r-1]['variable']]==filter_value
        limits = all_limits[condition]['expid'].tolist()
        #print(limits)
        all_exp = all_exp + limits
        #print(condition)
    all_exp = list( dict.fromkeys(all_exp) ) ## removed duplicates
    return all_exp

ae = FilterLimits(filter_df)
ae

[1195, 1196, 1197, 1198]

row_a =  dbc.Row([
        dbc.Col(
            [
                dashdataandtables.limit_types_table
            ],
            width=12,
            )])
    
row_b = dbc.Row([
        dbc.Col(
            [
                dashdataandtables.experiments_table
            ],
            width=12,
            )])

row_c = dbc.Row([
        dbc.Col(
            [
                dashdataandtables.result_types_table
            ],
            width=12,
            )])

row_d = dbc.Row([
        dbc.Col(
            [
                dashdataandtables.spin_dependency_table
            ],
            width=12,
            )])

row_e = dbc.Row([
       dbc.Col(
            [
                dashdataandtables.years_table
            ],
            width=12,
            )])

row_f = dbc.Row([
       dbc.Col(
            [
                dashdataandtables.greatest_hit_table
            ],
            width=12,
            )])

sidecolumn = dbc.Col(
            [
                row_a, row_b, row_c, row_d, row_e, row_f
            ],
            width=2,)

In [12]:
row1 =  dbc.Row([
        dbc.Col(
            [
                dashdataandtables.limit_types_table
            ],
            width=2,
            ),
        dbc.Col(
            [
                dashdataandtables.experiments_table
            ],
            width=2,
            ),
        dbc.Col(
            [
                dashdataandtables.result_types_table
            ],
            width=2,
            ),
        dbc.Col(
            [
                dashdataandtables.spin_dependency_table
            ],
            width=2,
            ),
       dbc.Col(
            [
                dashdataandtables.years_table
            ],
            width=2,
            ),
       dbc.Col(
            [
                dashdataandtables.greatest_hit_table
            ],
            width=2,
            ),
])
    

row2 = dbc.Row([dbc.Col(
            [
                dashdataandtables.limits_table
            ],
            width=12,),
               ])

row2_debug = dbc.Row([dbc.Col(
            [
                dashdataandtables.debug_dropdown_table
            ],
            width=12,),
               ])

#row3 = dbc.Row([dbc.Col(html.Div('List Here',id='tbl_out'),width=12,),])

row3_1 = dbc.Row([dbc.Col(
            [
                dashdataandtables.limits_table
            ],
            width=10,),
               ], className ="TABLE_ROW NOPADDING")


row3_1_debug = dbc.Row([dbc.Col(
            [
                dashdataandtables.debug_dropdown_table
            ],
            width=10,),
               ], className ="TABLE_ROW NOPADDING")

row3_2 = dbc.Row([dbc.Col(
            [
                dashdataandtables.plots_table
            ],
            width=10,),
               ],className ="TABLE_ROW NOPADDING")

row4 = html.Div([dcc.Store(id='plot_expids')])

form = dbc.Container(
    children=[dbc.Row(
    [
        row1,
        row2,
        #row2_debug,
        row3_1,
        row4
    ])],
    
)

In [13]:
dashdataandtables.limits_table_df.head(5)

,rowid,id,spin_dependency,experiment,official,greatest_hit,data_label,result_type,data_reference,year,expid
id,,,,,,,,,,,
1193,0,1193,SD,Experiment DMTOOL,1,0,dmtool,Th,dmtool,2023,1193
1194,1,1194,SD,Experiment D,1,0,d,Th,d,2023,1194
1195,2,1195,SD,Experiment M,1,0,m,Th,m,2020,1195
1196,3,1196,SD,Experiment T,1,0,t,Th,t,2020,1196
1197,4,1197,SD,Experiment O,1,0,o,Th,o,2020,1197

In [14]:
filter_df = pd.DataFrame(data=None,columns=['variable','label','value'])
filter_df.loc[0] = ['year',2023,2023]
filter_df.loc[1] = ['data_label','dmtool','dmtool']
filter_df

     variable   label   value
0        year    2023    2023
1  data_label  dmtool  dmtool

In [15]:
unfiltered_df = dashdataandtables.limits_table_df.copy()
#df.drop(df.index , inplace=True)
filtered_df = unfiltered_df.drop(unfiltered_df.index)
filtered_df

Empty DataFrame
Columns: [rowid, id, spin_dependency, experiment, official, greatest_hit, data_label, result_type, data_reference, year, expid]
Index: []

In [16]:
unfiltered_df = dashdataandtables.limits_table_df.copy()
#df.drop(df.index , inplace=True)
filtered_df = unfiltered_df.drop(unfiltered_df.index)
filtered_df

for index, row in filter_df.iterrows():
    #print(row['variable'], row['value'])
    matching_records = unfiltered_df[unfiltered_df[row['variable']] == row['value']]
    filtered_df = pd.concat([filtered_df, matching_records])
    #filtered_df = filtered_df[filtered_df[row['variable']] == row['value']] 
filtered_df = filtered_df.drop_duplicates()
filtered_df

,rowid,id,spin_dependency,experiment,official,greatest_hit,data_label,result_type,data_reference,year,expid
id,,,,,,,,,,,
1193,0,1193,SD,Experiment DMTOOL,1,0,dmtool,Th,dmtool,2023,1193
1194,1,1194,SD,Experiment D,1,0,d,Th,d,2023,1194

In [17]:
plots_todo_df = pd.DataFrame(data=None, \
                             columns=dashdataandtables.limits_table_df.columns, \
                             index=dashdataandtables.limits_table_df.index).copy()

In [18]:
plots_todo_df

,rowid,id,spin_dependency,experiment,official,greatest_hit,data_label,result_type,data_reference,year,expid
id,,,,,,,,,,,
1193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
maincolumn = dbc.Col(
            [
                row1,
                row3_1,
                #row3_1_debug,
                row3_2
            ],
            width=10,)

chartrow = dbc.Row([
    dbc.Col([
        dcc.Graph(id='basicgraph', responsive=True, style={
            'display': 'block'
        })
    ])
], className = "CHART_ROW NOPADDING")

charttwotablecolumn = dbc.Col(
            [
                chartrow,row3_1,row3_2
            ],
            width=10,)

twocolumns =  html.Div(className="row ALL_ROW NOPADDING",children=[sidecolumn,##column_chart,
                                                  charttwotablecolumn,],)

In [20]:
maindiv =  html.Div(className="row ALL_ROW NOPADDING",children=[maincolumn])

layout4 = html.Div([maindiv],
                   className="container-fluid MASTER_CONTAINER_STYLE",
                  )

#app.layout = layout4

In [21]:

app.layout = layout4

@callback(
    Output('limits_table_main', 'data'),
    #Output('debug_dropdown_table', 'data'),
    #Output(component_id='tbl_out', component_property='children'),
    #
    Input('years_table', 'active_cell'),
    Input('years_table', 'derived_virtual_selected_rows'),
    #
    Input('limit_types_table', 'active_cell'),
    Input('limit_types_table', 'derived_virtual_selected_rows'),
    #
    Input('experiments_table', 'active_cell'),
    Input('experiments_table', 'derived_virtual_selected_rows'),
    #
    Input('result_types_table', 'active_cell'),
    Input('result_types_table', 'derived_virtual_selected_rows'),
    #
    Input('spin_dependency_table', 'active_cell'),
    Input('spin_dependency_table', 'derived_virtual_selected_rows'),
    #
    Input('greatest_hit_table', 'active_cell'),
    Input('greatest_hit_table', 'derived_virtual_selected_rows'),
    )
def update_graphs(
    active_cell_years,
    derived_virtual_selected_rows_years,
    #
    active_cell_limit_types,
    derived_virtual_selected_rows_limit_types,
    #
    active_cell_experiments,
    derived_virtual_selected_rows_experiments,
    #
    active_cell_resulttypes,
    derived_virtual_selected_rows_result_types,
    #
    active_cell_spin_dependency,
    derived_virtual_selected_rows_spin_dependence,
    #
    active_cell_greatest_hit,
    derived_virtual_selected_rows_greatest_hit,
    
):
    
    try:
        dfs = [
            dashdataandtables.years_df.loc[derived_virtual_selected_rows_years],
            dashdataandtables.limit_types_df.loc[derived_virtual_selected_rows_limit_types],
            dashdataandtables.experiments_df.loc[derived_virtual_selected_rows_experiments],
            dashdataandtables.result_types_df.loc[derived_virtual_selected_rows_result_types],
            dashdataandtables.spin_dependence_df.loc[derived_virtual_selected_rows_spin_dependence],
            dashdataandtables.greatest_hit_df.loc[derived_virtual_selected_rows_greatest_hit]
        ]
        non_empty_dfs = [df for df in dfs if not df.empty]
        all_filters_df = pd.concat(non_empty_dfs)
    except:
        all_filters_df = pd.DataFrame()
    
    # https://stackoverflow.com/questions/60964165/ignore-empty-dataframe-when-merging
    
    unfiltered_df = dashdataandtables.limits_table_df.copy()
    #df.drop(df.index , inplace=True)
    
    filtered_df = unfiltered_df.drop(unfiltered_df.index)
    #filtered_df
    
    if all_filters_df.empty:
        filtered_df = unfiltered_df
    else:
        for index, row in all_filters_df.iterrows():
            #print(row['variable'], row['value'])
            matching_records = unfiltered_df[unfiltered_df[row['variable']] == row['value']]
            filtered_df = pd.concat([filtered_df, matching_records])
            #filtered_df = matching_records
            #filtered_df = filtered_df[filtered_df[row['variable']] == row['value']] 
    
    filtered_df = filtered_df.drop_duplicates()
    #filtered_df
   
    data1 = all_filters_df.to_dict("records")
    data2 = filtered_df.to_dict("records")
    print(data1)
    #data1=dff2.to_dict("records")
    #list_output = str(selectedcontinent_list) if selectedcontinent_list else "Click the table"
    return data2 #, list_output


@callback(
    Output('plots_table', 'data'),
    [Input('limits_table_main', 'active_cell'),Input('plots_table', 'active_cell')],
    [State('plots_table', 'data')])
def trigger_fork(active_cell_exp,active_cell_plot,data_in):
    ctx = dash.callback_context
    triggered_id = ctx.triggered[0]['prop_id'].split('.')[0]
    print(triggered_id)
    if triggered_id == 'limits_table_main':

        selected_rowid = active_cell_exp['row_id']
        selected_row = dashdataandtables.\
                limits_table_df[dashdataandtables.limits_table_df['expid']==active_cell_exp['row_id']]
        selected_row  = selected_row[['expid','data_reference','data_reference','data_label']]
        #data_out=plots_todo_df.to_dict("records")
        record=selected_row.to_dict("records")[0]
        #print(type(record))
        #print(record)
        #record = {columns[i]: arg for i, arg in enumerate(list(args))}
        # If the record (identified by user_key) already exists, update it.
        #try:
        #    #record_index = [record[selected_rowid] for record in data_in].index(record[selected_rowid])
        #    record_index = [record[selected_rowid] for record in data_in].index(record[selected_rowid])
        #    data_in[record_index] = record
        # Otherwise, append it.
        #except ValueError:
        #    data_in[selected_rowid] = record
        #dictlen = len(data_in)
        #data_in[selected_rowid] = record
        data_in.append(record)
        #data_in = record
        # Return the updated data.
        #return data

        #selected_row = limits_table_df[limits_table_df['expid']==active_cell['row_id']]
        #plots_todo_df= selected_row.copy()
        #data_out=plots_todo_df.to_dict("records")
        #data_out=selected_row.to_dict("records")

    elif triggered_id == 'plots_table':
        #selected_rowid = active_cell_plot['row']
        #print(data_in[selected_rowid])
        print(active_cell_plot)
        #data_in = data_in.pop(active_cell_plot['row'])
        print(data_in)
    
    return data_in

In [22]:

app.run_server(host="0.0.0.0", port=8002,debug=True)
#app.run_server(debug=True,port=5051)

Dash is running on http://0.0.0.0:8002/dash1/

Dash app running on http://0.0.0.0:8002/dash1/

In [23]:
dashdataandtables.limits_table_df

,rowid,id,spin_dependency,experiment,official,greatest_hit,data_label,result_type,data_reference,year,expid
id,,,,,,,,,,,
1193,0,1193,SD,Experiment DMTOOL,1,0,dmtool,Th,dmtool,2023,1193
1194,1,1194,SD,Experiment D,1,0,d,Th,d,2023,1194
1195,2,1195,SD,Experiment M,1,0,m,Th,m,2020,1195
1196,3,1196,SD,Experiment T,1,0,t,Th,t,2020,1196
1197,4,1197,SD,Experiment O,1,0,o,Th,o,2020,1197
1198,5,1198,SD,Experiment L,1,0,l,Th,l,2020,1198

[]
[]
limits_table_main

/tmp/ipykernel_137591/680732825.py:105: UserWarning:

DataFrame columns are not unique, some columns will be omitted.

[]
[]
limits_table_main
limits_table_main
limits_table_main
[{'variable': 'experiment', 'label': 'Experiment DMTOOL', 'value': 'Experiment DMTOOL', 'data_type': 'text'}]
[]
[{'variable': 'experiment', 'label': 'Experiment D', 'value': 'Experiment D', 'data_type': 'text'}]
[]
[{'variable': 'result_type', 'label': 'Project', 'value': 'Proj', 'data_type': 'text'}]
[]
[{'variable': 'result_type', 'label': 'Experiment', 'value': 'Exp', 'data_type': 'text'}]
[]
[{'variable': 'result_type', 'label': 'Theory', 'value': 'Th', 'data_type': 'text'}]
[]


@callback(
    Output(component_id='tbl_out', component_property='children'),
    #
    Input('limits_table_main', 'active_cell'),
    ##Input('limits_table', 'derived_virtual_selected_rows'),
    Input('limits_table_main', 'selected_rows')
    #Input('limits_table', 'selected_row_ids') #,
    #derived_viewport_selected_row_ids
)
def update_list(active_cell_limits,derived_virtual_selected_rows_limits):
    selected_limits_df = limits_table_df.loc[derived_virtual_selected_rows_limits]
    selected_ids = selected_limits_df['expid'].tolist()
    list_output = selected_ids
    return list_output #, list_output

@callback(
    Output('plots_table', 'data'),
    [Input('limits_table', 'active_cell'),Input('plots_table', 'active_cell')],
    [State('plots_table', 'data')])
def trigger_fork(active_cell_exp,active_cell_plot,data_in):
    ctx = dash.callback_context
    triggered_id = ctx.triggered[0]['prop_id'].split('.')[0]
    print(triggered_id)
    if triggered_id == 'limits_table':

        #record = {columns[i]: arg for i, arg in enumerate(list(args))}

        selected_rowid = active_cell_exp['row_id']
        selected_row = dashdataandtables.\
                limits_table_df[dashdataandtables.limits_table_df['expid']==active_cell_exp['row_id']]
        selected_row  = selected_row[['expid','data_reference','data_reference','data_label']]
        #data_out=plots_todo_df.to_dict("records")
        record=selected_row.to_dict("records")[0]
        #print(type(record))
        #print(record)
        #record = {columns[i]: arg for i, arg in enumerate(list(args))}
        # If the record (identified by user_key) already exists, update it.
        #try:
        #    #record_index = [record[selected_rowid] for record in data_in].index(record[selected_rowid])
        #    record_index = [record[selected_rowid] for record in data_in].index(record[selected_rowid])
        #    data_in[record_index] = record
        # Otherwise, append it.
        #except ValueError:
        #    data_in[selected_rowid] = record
        #dictlen = len(data_in)
        #data_in[selected_rowid] = record
        data_in.append(record)
        #data_in = record
        # Return the updated data.
        #return data

        #selected_row = limits_table_df[limits_table_df['expid']==active_cell['row_id']]
        #plots_todo_df= selected_row.copy()
        #data_out=plots_todo_df.to_dict("records")
        #data_out=selected_row.to_dict("records")

    elif triggered_id == 'plots_table':
        #selected_rowid = active_cell_plot['row']
        #print(data_in[selected_rowid])
        print(active_cell_plot)
        #data_in = data_in.pop(active_cell_plot['row'])
        print(data_in)
    
    return data_in

https://dash.plotly.com/datatable/interactivity

 
    selected_limit_types_df = dashdataandtables.limit_types_df.loc[derived_virtual_selected_rows_limit_types]
    selected_limit_types_list = list(selected_limit_types_df['label'])
    
    selected_experiments_df = dashdataandtables.experiments_df.loc[derived_virtual_selected_rows_experiments]
    selected_experiments_list = list(selected_experiments_df['label'])
    
    print(selected_experiments_list)
    
    selected_result_types_df = dashdataandtables.result_types_df.loc[derived_virtual_selected_rows_resulttypes]
    selected_result_types_list = list(selected_result_types_df['label'])
    
    selected_result_types_list_abbr = []
    
    for rt in selected_result_types_list:
        append_this = ''
        if rt == 'Theory':
            append_this = 'Th'
        elif rt == 'Project':
            append_this = 'Proj'
        elif rt == 'Experiment':
            append_this = 'Exp'
        else:
            append_this = rt
        selected_result_types_list_abbr.append(append_this)
            
    
    selected_spin_dependency_df = \
            dashdataandtables.spin_dependency_df.loc[derived_virtual_selected_rows_spin_dependency]
    selected_spin_dependency_list = \
            list(selected_spin_dependency_df['label'])
    
    selected_spin_dependency_list_abbr = []
    
    for sd in selected_spin_dependency_list:
        append_this = ''
        if sd == 'spin-dependent':
            append_this = 'SD'
        elif sd == 'spin-indpendent':
            append_this = 'SI'
        else:
            append_this = sd
        selected_spin_dependency_list_abbr.append(append_this)
    
    selected_greatest_hit_df = \
            dashdataandtables.greatest_hit_df.loc[derived_virtual_selected_rows_greatest_hit]
    selected_greatest_hit_list = list(selected_greatest_hit_df['label'])
    
    selected_greatest_hit_list_abbr = []    
    
    for gh in selected_greatest_hit_list:
        append_this = ''
        if gh == 'No':
            append_this = 0
        elif gh == 'Yes':
            append_this = 1
        else:
            append_this = gh
        selected_greatest_hit_list_abbr.append(append_this)
    
    
    if selected_years_df.empty:
        dff1 = dashdataandtables.limits_table_df
    else:
        dff1 = dashdataandtables.limits_table_df[dashdataandtables.limits_table_df['year'].\
                                              isin(selected_years_list)].copy()

 try:
        for s in selected_experiments_list:
            append_this = pd.DataFrame(data=['experiments', s],columns=['variable','value'])
            filter_df = pd.concat([filter_df, append_this])
    except:
        print('experiments')
    
    try:
        for s in selected_result_types_list:
            append_this = pd.DataFrame(data=['result_type', s],columns=['variable','value'])
            filter_df = pd.concat([filter_df, append_this])
    except:
        print('result_type')
    
    try:
        for s in selected_greatest_hit_list:
            append_this = pd.DataFrame(data=['greatest_hit', s],columns=['variable','value'])
            filter_df = pd.concat([filter_df, append_this])
    except:
        print('greatest_hit')
        
    try:
        for s in selected_spin_dependency_df:
            append_this = pd.DataFrame(data=['spin_dependence', s],columns=['variable','value'])
            filter_df = pd.concat([filter_df, append_this])
    except:
        print('spin_dependence')
        
    try:
        for s in selected_limit_types_list:
            append_this = pd.DataFrame(data=['limit_type', s],columns=['variable','value'])
            filter_df = pd.concat([filter_df, append_this])
    except:
        print('limit_type')

filter_df = pd.DataFrame(data=[],columns=['variable','value'])
    
    selected_years_df = dashdataandtables.years_df.loc[derived_virtual_selected_rows_years]
    if selected_years_df.empty:
        selected_years_list = []
    else:
        selected_years_list = list(selected_years_df['year'])
    
    for s in selected_years_list:
        append_this = pd.DataFrame(data=['year', s],columns=['variable','value'])
        filter_df = pd.concat([filter_df, append_this])
    
    print(filter_df)
    
    selected_limit_types_df = dashdataandtables.limit_types_df.loc[derived_virtual_selected_rows_limit_types]
    selected_limit_types_list = list(selected_limit_types_df['label'])
    
    selected_experiments_df = dashdataandtables.experiments_df.loc[derived_virtual_selected_rows_experiments]
    selected_experiments_list = list(selected_experiments_df['label'])
    
    print(selected_experiments_list)
    
    selected_result_types_df = dashdataandtables.result_types_df.loc[derived_virtual_selected_rows_resulttypes]
    selected_result_types_list = list(selected_result_types_df['label'])
    
    selected_result_types_list_abbr = []
    
    for rt in selected_result_types_list:
        append_this = ''
        if rt == 'Theory':
            append_this = 'Th'
        elif rt == 'Project':
            append_this = 'Proj'
        elif rt == 'Experiment':
            append_this = 'Exp'
        else:
            append_this = rt
        selected_result_types_list_abbr.append(append_this)
            
    
    selected_spin_dependency_df = \
            dashdataandtables.spin_dependency_df.loc[derived_virtual_selected_rows_spin_dependency]
    selected_spin_dependency_list = \
            list(selected_spin_dependency_df['label'])
    
    selected_spin_dependency_list_abbr = []
    
    for sd in selected_spin_dependency_list:
        append_this = ''
        if sd == 'spin-dependent':
            append_this = 'SD'
        elif sd == 'spin-indpendent':
            append_this = 'SI'
        else:
            append_this = sd
        selected_spin_dependency_list_abbr.append(append_this)
    
    selected_greatest_hit_df = \
            dashdataandtables.greatest_hit_df.loc[derived_virtual_selected_rows_greatest_hit]
    selected_greatest_hit_list = list(selected_greatest_hit_df['label'])
    
    selected_greatest_hit_list_abbr = []    
    
    for gh in selected_greatest_hit_list:
        append_this = ''
        if gh == 'No':
            append_this = 0
        elif gh == 'Yes':
            append_this = 1
        else:
            append_this = gh
        selected_greatest_hit_list_abbr.append(append_this)
    
    
    if selected_years_df.empty:
        dff1 = dashdataandtables.limits_table_df
    else:
        dff1 = dashdataandtables.limits_table_df[dashdataandtables.limits_table_df['year'].\
                                              isin(selected_years_list)].copy()

    if selected_limit_types_df.empty:
        dff2 = dff1
    else:
        if selected_limit_types_list[0] == 'All Limits':
            dff2 = dff1
        else:
            dff2 = dff1[dff1['official']==1].copy()
    
    if selected_experiments_df.empty:
        dff1 = dff2
    else:
        dff1 = dff2[dff2['experiment'].isin(selected_experiments_list)].copy()

    if selected_result_types_df.empty:
        dff2 = dff1
    else:
        dff2 = dff1[dff1['result_type'].isin(selected_result_types_list_abbr)].copy()

    if selected_spin_dependency_df.empty:
        dff1 = dff2
    else:
        dff1 = dff2[dff2['spin_dependency'].isin(selected_spin_dependency_list_abbr)].copy()
    
    if selected_greatest_hit_df.empty:
        dff2 = dff1
    else:
        dff2 = dff1[dff1['greatest_hit'].isin(selected_greatest_hit_list_abbr)].copy()
    
    #selected_ids = dff2['id'].tolist()
    
    #list_output = ['Hello','Everyone']
    #list_output = selected_greatest_hit_list
    #list_output = selected_ids
    #if not selected_band_list:
    #    dff2 = dff1.copy()
    #else:
    #    dff2 = dff1[dff1['band'].isin(selected_band_list)].copy()

    #active_row_id = active_cell['row_id'] if active_cell else None

    data1=dff2.to_dict("records")
    #list_output = str(selectedcontinent_list) if selectedcontinent_list else "Click the table"

if selected_limit_types_df.empty:
        dff2 = dff1
    else:
        if selected_limit_types_list[0] == 'All Limits':
            dff2 = dff1
        else:
            dff2 = dff1[dff1['official']==1].copy()
    
    if selected_experiments_df.empty:
        dff1 = dff2
    else:
        dff1 = dff2[dff2['experiment'].isin(selected_experiments_list)].copy()

    if selected_result_types_df.empty:
        dff2 = dff1
    else:
        dff2 = dff1[dff1['result_type'].isin(selected_result_types_list_abbr)].copy()

    if selected_spin_dependency_df.empty:
        dff1 = dff2
    else:
        dff1 = dff2[dff2['spin_dependency'].isin(selected_spin_dependency_list_abbr)].copy()
    
    if selected_greatest_hit_df.empty:
        dff2 = dff1
    else:
        dff2 = dff1[dff1['greatest_hit'].isin(selected_greatest_hit_list_abbr)].copy()
        
        '''
@callback(
    Output(component_id='tbl_out', component_property='children'),
    #
    Input('limits_table', 'active_cell'),
    ##Input('limits_table', 'derived_virtual_selected_rows'),
    Input('limits_table', 'selected_rows')
    #Input('limits_table', 'selected_row_ids') #,
    #derived_viewport_selected_row_ids
)
def update_list(
        active_cell_limits,
        derived_virtual_selected_rows_limits):
        selected_limits_df = limits_table_df.loc[derived_virtual_selected_rows_limits]
        selected_ids = selected_limits_df['expid'].tolist()
        list_output = selected_ids
        return list_output #, list_output
'''