In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html

import plotly.graph_objects as go


from dash import Dash, Input, Output, callback

from jupyter_dash import JupyterDash

import dash_bootstrap_components as dbc
COMPONENT_STYLE = "/assets/my_component.css"
external_stylesheets=[dbc.themes.BOOTSTRAP]

app = JupyterDash(__name__, external_stylesheets=external_stylesheets,
                  meta_tags=[{'name': 'viewport', 'content': 'width=device-width, initial-scale=1'}],
                 suppress_callback_exceptions=True)
# Create server variable with Flask server object for use with gunicorn
server = app.server

/tmp/ipykernel_29068/3871165922.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/tmp/ipykernel_29068/3871165922.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [2]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine
import psycopg2
engine = create_engine('mysql://pythonuser:pythonuser@localhost:3306/RubyDB')
sqlquery = '''SELECT id, name FROM RubyDB.experiments;'''
experiments_df = pd.read_sql_query(sqlquery, engine)
experiments_df

    id              name
0    1      CDMS I (SUF)
1    2  CDMS II (Soudan)
2    3         SuperCDMS
3    4               LUX
4    5           XENON10
..  ..               ...
56  60            GAMBIT
57  63           CDEX-10
58  64            NEWS-G
59  65           XENONnT
60  66            CRESST

[61 rows x 2 columns]

# XML Reading

In [4]:
import xml.etree.ElementTree as ET
tree = ET.parse('example.xml')
root = tree.getroot()
#dv_find = root.findall('data-values')
#data = dv_find[0].text

In [5]:
def find_xml_text(root_in,tag_in):
    dv_find = root_in.findall(tag_in)
    return dv_find[0].text

In [6]:
data_values = find_xml_text(root,'data-values')
data_comment = find_xml_text(root,'data-comment')

In [7]:
data_label = find_xml_text(root,'data-label')
data_reference = find_xml_text(root,'data-reference')
date_of_announcement = find_xml_text(root,'date-of-announcement')
date_of_run_end = find_xml_text(root,'date-of-run-end')
date_of_run_start = find_xml_text(root,'date-of-run-start')
default_color = find_xml_text(root,'default-color')

default_style = find_xml_text(root,'default-style')
experiment = find_xml_text(root,'experiment')
public = find_xml_text(root,'public')
result_type = find_xml_text(root,'result-type')
spin_dependency = find_xml_text(root,'spin-dependency')
x_rescale = find_xml_text(root,'x-rescale')
x_units = find_xml_text(root,'x-units')
y_rescale = find_xml_text(root,'y-rescale')
y_units = find_xml_text(root,'y-units')
year = find_xml_text(root,'year')

# SQL

In [8]:
##sqlquery = '''SELECT id, name FROM RubyDB.experiments;'''


sqlquery = '''SELECT
id, spin_dependency, result_type, measurement_type, nomhash, x_units, y_units, x_rescale,
y_rescale, default_color, default_style,
data_values, data_label, file_name, data_comment,
data_reference, created_at, updated_at, creator_id, experiment, rating, date_of_announcement,
public, official, date_official, greatest_hit, date_of_run_start, date_of_run_end, `year`
FROM RubyDB.limits;'''

limits_df = pd.read_sql_query(sqlquery, engine)
limits_df

,id,spin_dependency,result_type,measurement_type,nomhash,x_units,y_units,x_rescale,y_rescale,default_color,...,experiment,rating,date_of_announcement,public,official,date_official,greatest_hit,date_of_run_start,date_of_run_end,year
0,1,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,,,LtR,...,Theory,0,2003-01-01,1,1,None,0,None,None,2003.0
1,2,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
2,3,SD,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
3,4,SD,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
4,5,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,,,LtB,...,Theory,0,2003-01-01,1,1,None,0,None,None,2003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,1115,SD,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1,Blk,...,XENONnT,0,None,1,0,None,0,None,None,2020.0
951,1116,SI,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1e-36,Blk,...,CRESST,0,None,1,0,None,0,None,None,2019.0
952,1117,SD,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1e-36,Blk,...,CRESST,0,None,1,0,None,0,None,None,2019.0
953,1118,SI,Personal,Dir,b'--- \nandreyalexandrov: false\n',GeV,cm^2,1,1,Blk,...,,0,None,0,0,None,0,None,None,2021.0
954,1119,SI,Personal,Dir,b'--- \nandreyalexandrov: false\n',GeV,cm^2,1,1,Blk,...,,0,None,0,0,None,0,None,None,2021.0

In [9]:
#data_df = []
data_record = [[data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,
               date_of_run_start,default_color,default_style,experiment,
               public,result_type,spin_dependency,x_rescale,x_units,y_rescale,
               y_units,year
              ]]
data_df = pd.DataFrame.from_records(data=data_record, columns = ['data_values','data_comment','data_label','data_reference','date_of_announcement','date_of_run_end',
               'date_of_run_start','default_color','default_style','experiment',
               'public','result_type','spin_dependency','x_rescale','x_units','y_rescale',
               'y_units','year'])
data_df

#data_df['id'] = df['country']
#df.set_index('id', inplace=True, drop=False)
#data_df.index.name = 'id'
#data_df['id'] = data_df.index
data_df

,data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,date_of_run_start,default_color,default_style,experiment,public,result_type,spin_dependency,x_rescale,x_units,y_rescale,y_units,year
0,{[98.69386 2.679186e-08;117.6216 2.626349e-08;...,Markov chain monte carlo contours in CMSSM.,"Trotta et. al., 2008, CMSSM Bayesian: 68% cont...",arXiv:0809.3792,2008-01-01,None,None,DkB,Fill,Theory,true,Th,SI,1,GeV,1e-36,cm^2,2008

#string_data = ET.tostring(data, encoding="unicode")
#string_data
#data


data = data.replace("{[", "")
data = data.replace("]}", "")
x = data.split(";")
lol = []
for i in x:
    z = i.split(" ");
    appendthis = [z[0],z[1]]
    lol.append(appendthis)
#lol
df_experiment = pd.DataFrame(data=lol,columns=['raw_x','raw_y'])

df_experiment['x'] = df_experiment['raw_x'].astype(str).astype(float)
df_experiment['y'] = df_experiment['raw_y'].astype(str).astype(float)

df_experiment.dtypes

df_experiment.plot.scatter(x='x',y='y')

# Drop Down

In [10]:
#https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/

#x range (WIMP mass) 	lower bound: 	to 	upper bound: 	GeV/c^2
#y range (cross-section) 	smallest c-s: 10^ 	to 	largest c-s: 10^ 	
#Table
#Result	Reference	Plot appearance

ResultTypeDropdown = dcc.Dropdown(
        id='resulttype-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'Experiment', 'value': 'Experiment'},
            {'label': 'Projection', 'value': 'Projection'},
            {'label': 'Theory', 'value': 'Theory'},
            {'label': 'Other', 'value': 'Other'},
            {'label': 'Personal', 'value': 'Personal'}            
        ],
        value='All'
    )

#dbc.DropdownMenu(
#    label="Menu",
#    children=[
#        dbc.DropdownMenuItem("Item 1"),
#        dbc.DropdownMenuItem("Item 2"),
#        dbc.DropdownMenuItem("Item 3"),
#    ],
#)

SpinDropdown = dcc.Dropdown(
        id='spin-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'spin-dependent', 'value': 'spin-dependent'},
            {'label': 'spin-indpendent', 'value': 'spin-indpendent'}    
        ],
        value='All'
    )


ExperimentDropdown = dcc.Dropdown(
        id='experiment-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'CDEX-10', 'value': ''},
            {'label': 'CDMS I (SUF)', 'value': ''},
            {'label': 'CDMS II (Soudan)', 'value': ''},
            {'label': 'CDMS II (Soudan)', 'value': ''},
            {'label': 'COSME', 'value': ''},
            {'label': 'COUPP', 'value': ''},
            {'label': 'COURICIONO', 'value': ''},
            {'label': 'CoGeNT', 'value': ''},
            {'label': 'Cuore', 'value': ''}
        ],
        value='All'
    )

YearDropdown = dcc.Dropdown(
        id='year-dropdown',
        options=[
            {'label': '2000', 'value': '2000'},
            {'label': '2001', 'value': '2001'},
            {'label': '2002', 'value': '2002'},
            {'label': '2003', 'value': '2003'},
            {'label': '2004', 'value': '2004'},
            {'label': '2005', 'value': '2005'},
            {'label': '2006', 'value': '2006'},
            {'label': '2007', 'value': '2007'},
            {'label': '2008', 'value': '2008'},
            {'label': '2009', 'value': '2009'},
            {'label': '2010', 'value': '2010'},
            {'label': '2011', 'value': '2011'},
            {'label': '2012', 'value': '2012'},
            {'label': '2013', 'value': '2013'},
            {'label': '2014', 'value': '2014'},
            {'label': '2015', 'value': '2015'},
            {'label': '2016', 'value': '2016'},
            {'label': '2017', 'value': '2017'},
            {'label': '2018', 'value': '2018'},
            {'label': '2019', 'value': '2019'},
            {'label': '2020', 'value': '2020'}
        ],
        value='All'
    )

GreatestHitsDropdown = dcc.Dropdown(
        id='greatesthits-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'Greatest Hits', 'value': 'Greatest Hits'}
        ],
        value='All'
    )

#List of Research Results

#Result	Reference

In [11]:
import dash_bootstrap_components as dbc

form = dbc.Container(
    children=[dbc.Row(
    [
        dbc.Col(
            [
                dbc.Label("Result Type"),
                ResultTypeDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Spin"),
                SpinDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Experiment"),
                ExperimentDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Year"),
                YearDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Greatest Hits"),
                GreatestHitsDropdown,
            ],
            width=2,
        ),
    ],
    className="g-3",
)])

In [12]:
from dash import dash_table

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

table1 = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)

In [13]:
df = pd.read_csv('https://git.io/Juf1t')

table2 = dbc.Container([
    dbc.Label('Click a cell in the table:'),
    dash_table.DataTable(
        id='tbl', data=df.to_dict('records'),
        columns=[{"name": i, "id": i} for i in df.columns],
    ),
    dbc.Alert(id='tbl_out'),
])

@callback(Output('tbl_out', 'children'), Input('tbl', 'active_cell'))
def update_graphs(active_cell):
    return str(active_cell) if active_cell else "Click the table"

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')
# add an id column and set it as the index
# in this case the unique ID is just the country name, so we could have just
# renamed 'country' to 'id' (but given it the display name 'country'), but
# here it's duplicated just to show the more general pattern.
df['id'] = df['country']
df.set_index('id', inplace=True, drop=False)
df

,country,pop,continent,lifeExp,gdpPercap,id
id,,,,,,
Afghanistan,Afghanistan,31889923.0,Asia,43.828,974.580338,Afghanistan
Albania,Albania,3600523.0,Europe,76.423,5937.029526,Albania
Algeria,Algeria,33333216.0,Africa,72.301,6223.367465,Algeria
Angola,Angola,12420476.0,Africa,42.731,4797.231267,Angola
Argentina,Argentina,40301927.0,Americas,75.320,12779.379640,Argentina
...,...,...,...,...,...,...
Vietnam,Vietnam,85262356.0,Asia,74.249,2441.576404,Vietnam
West Bank and Gaza,West Bank and Gaza,4018332.0,Asia,73.422,3025.349798,West Bank and Gaza
"Yemen, Rep.","Yemen, Rep.",22211743.0,Asia,62.698,2280.769906,"Yemen, Rep."
Zambia,Zambia,11746035.0,Africa,42.384,1271.211593,Zambia
Zimbabwe,Zimbabwe,12311143.0,Africa,43.487,469.709298,Zimbabwe

layout_1 = html.Div([
    dash_table.DataTable(
        id='datatable-row-ids',
        columns=[
            {'name': i, 'id': i, 'deletable': True} for i in df.columns
            # omit the id column
            if i != 'id'
        ],
        data=df.to_dict('records'),
        editable=False,
        filter_action="native",
        sort_action="native",
        sort_mode='multi',
        row_selectable='single',
        row_deletable=False,
        selected_rows=[],
        page_action='native',
        page_current= 0,
        page_size= 10,
    ),
    html.Div(id='datatable-row-ids-container')
])


@app.callback(
    Output('datatable-row-ids-container', 'children'),
    Input('datatable-row-ids', 'derived_virtual_row_ids'),
    Input('datatable-row-ids', 'selected_row_ids'),
    Input('datatable-row-ids', 'active_cell'))
def update_graphs(row_ids, selected_row_ids, active_cell):
    # When the table is first rendered, `derived_virtual_data` and
    # `derived_virtual_selected_rows` will be `None`. This is due to an
    # idiosyncrasy in Dash (unsupplied properties are always None and Dash
    # calls the dependent callbacks when the component is first rendered).
    # So, if `rows` is `None`, then the component was just rendered
    # and its value will be the same as the component's dataframe.
    # Instead of setting `None` in here, you could also set
    # `derived_virtual_data=df.to_rows('dict')` when you initialize
    # the component.
    selected_id_set = set(selected_row_ids or [])

    if row_ids is None:
        dff = df
        # pandas Series works enough like a list for this to be OK
        row_ids = df['id']
    else:
        dff = df.loc[row_ids]

    active_row_id = active_cell['row_id'] if active_cell else None

    colors = ['#FF69B4' if id == active_row_id
              else '#7FDBFF' if id in selected_id_set
              else '#0074D9'
              for id in row_ids]

    return [
        dcc.Graph(
            id=column + '--row-ids',
            figure={
                'data': [
                    {
                        'x': dff['country'],
                        'y': dff[column],
                        'type': 'bar',
                        'marker': {'color': colors},
                    }
                ],
                'layout': {
                    'xaxis': {'automargin': True},
                    'yaxis': {
                        'automargin': True,
                        'title': {'text': column}
                    },
                    'height': 250,
                    'margin': {'t': 10, 'l': 10, 'r': 10},
                },
            },
        )
        # check if column exists - user may have deleted it
        # If `column.deletable=False`, then you don't
        # need to do this check.
        #for column in ['pop', 'lifeExp', 'gdpPercap'] if column in dff
        for column in ['pop'] if column in dff
    ]

In [15]:
def datastring2dataframe(data_values_in):
    try:
        data_list = data_values_in['data_values'].tolist()
        data_string = data_list[0]
        data_string = data_string.replace("{[", "")
        data_string = data_string.replace("]}", "")
        x = data_string.split(";")
        lol = []
        for i in x:
            z = i.split(" ");
            appendthis = [z[0],z[1]]
            lol.append(appendthis)
        #lol
        df_experiment = pd.DataFrame(data=lol,columns=['raw_x','raw_y'])

        df_experiment['x'] = df_experiment['raw_x'].astype(str).astype(float)
        df_experiment['y'] = df_experiment['raw_y'].astype(str).astype(float)
    except:
        data_null = [[0,0]]
        df_experiment = pd.DataFrame(data=data_null,columns=['raw_x','raw_y'])

        df_experiment['x'] = df_experiment['raw_x'].astype(str).astype(float)
        df_experiment['y'] = df_experiment['raw_y'].astype(str).astype(float)
    #df_experiment.dtypes
    return df_experiment

In [16]:
data_df.dtypes

data_values             object
data_comment            object
data_label              object
data_reference          object
date_of_announcement    object
date_of_run_end         object
date_of_run_start       object
default_color           object
default_style           object
experiment              object
public                  object
result_type             object
spin_dependency         object
x_rescale               object
x_units                 object
y_rescale               object
y_units                 object
year                    object
dtype: object

In [17]:
dict_ex = datastring2dataframe(limits_df[['data_values']]).to_dict('records')
#dict_ex = df_ex.to_dict('records')
dict_ex
##data_list = data_df['data_values'].tolist()
##data_list[0]

[{'raw_x': '60', 'raw_y': '4e-43', 'x': 60.0, 'y': 4e-43},
 {'raw_x': '70', 'raw_y': '4e-43', 'x': 70.0, 'y': 4e-43},
 {'raw_x': '160', 'raw_y': '5.5e-44', 'x': 160.0, 'y': 5.5e-44},
 {'raw_x': '320', 'raw_y': '2.5e-44', 'x': 320.0, 'y': 2.5e-44},
 {'raw_x': '630', 'raw_y': '3.2e-44', 'x': 630.0, 'y': 3.2e-44},
 {'raw_x': '640', 'raw_y': '3e-44', 'x': 640.0, 'y': 3e-44},
 {'raw_x': '640', 'raw_y': '1.2e-44', 'x': 640.0, 'y': 1.2e-44},
 {'raw_x': '630', 'raw_y': '1e-44', 'x': 630.0, 'y': 1e-44},
 {'raw_x': '225', 'raw_y': '9e-45', 'x': 225.0, 'y': 9e-45},
 {'raw_x': '215', 'raw_y': '7e-45', 'x': 215.0, 'y': 7e-45},
 {'raw_x': '315', 'raw_y': '7e-46', 'x': 315.0, 'y': 7e-46},
 {'raw_x': '470', 'raw_y': '2.1e-46', 'x': 470.0, 'y': 2.1e-46},
 {'raw_x': '650', 'raw_y': '7e-47', 'x': 650.0, 'y': 7e-47},
 {'raw_x': '660', 'raw_y': '6.8e-47', 'x': 660.0, 'y': 6.8e-47},
 {'raw_x': '660', 'raw_y': '2e-47', 'x': 660.0, 'y': 2e-47},
 {'raw_x': '650', 'raw_y': '2e-47', 'x': 650.0, 'y': 2e-47},
 {'raw_x': '470', 'raw_y': '6e-47', 'x': 470.0, 'y': 6e-47},
 {'raw_x': '315', 'raw_y': '1e-46', 'x': 315.0, 'y': 1e-46},
 {'raw_x': '215', 'raw_y': '3e-46', 'x': 215.0, 'y': 3e-46},
 {'raw_x': '100', 'raw_y': '8e-46', 'x': 100.0, 'y': 8e-46},
 {'raw_x': '60', 'raw_y': '1e-45', 'x': 60.0, 'y': 1e-45},
 {'raw_x': '60', 'raw_y': '4e-43', 'x': 60.0, 'y': 4e-43}]

In [18]:
dv = limits_df[limits_df['id']==100][['data_values']]
oneid = limits_df[limits_df['id']==100]
#limits_df.columns
oneid = oneid[[
'id',
'data_values',         
'data_comment',
'data_label',
'data_reference',
'date_of_announcement',
'date_of_run_end',
'date_of_run_start',
'default_color',
'default_style',
'experiment',
'public',
'result_type',
'spin_dependency',
'x_rescale',
'x_units',
'y_rescale',
'y_units',
'year']]
oneid.dtypes

id                        int64
data_values              object
data_comment             object
data_label               object
data_reference           object
date_of_announcement     object
date_of_run_end          object
date_of_run_start        object
default_color            object
default_style            object
experiment               object
public                    int64
result_type              object
spin_dependency          object
x_rescale                object
x_units                  object
y_rescale                object
y_units                  object
year                    float64
dtype: object

In [19]:
allid = limits_df.copy()
#limits_df.columns
allid = allid[[
'id',
'data_values',         
'data_comment',
'data_label',
'data_reference',
'date_of_announcement',
'date_of_run_end',
'date_of_run_start',
'default_color',
'default_style',
'experiment',
'public',
'result_type',
'spin_dependency',
'x_rescale',
'x_units',
'y_rescale',
'y_units',
'year']]
allid.dtypes

id                        int64
data_values              object
data_comment             object
data_label               object
data_reference           object
date_of_announcement     object
date_of_run_end          object
date_of_run_start        object
default_color            object
default_style            object
experiment               object
public                    int64
result_type              object
spin_dependency          object
x_rescale                object
x_units                  object
y_rescale                object
y_units                  object
year                    float64
dtype: object

In [20]:
selected_id_set = [100]
    
#value_list = ["apple"]
boolean_series = allid.id.isin(selected_id_set)

filtered_df = allid[boolean_series]

filtered_df

,id,data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,date_of_run_start,default_color,default_style,experiment,public,result_type,spin_dependency,x_rescale,x_units,y_rescale,y_units,year
98,100,{[2.759 8.997e-35;2.845 5.824e-35;2.934 3.875e...,"Sigma for vector coupled WIMP, normalized to X...","Edelweiss, 1996, Al2-O3 detector, SI",Astroparticle Physics 6 (1996) 35-43,1996-01-01,None,None,Red,Line,Edelweiss,1,Exp,SI,,GeV,,cm^2,1996.0

In [21]:
data_df.dtypes
x = data_df['y_units'][0]
type(x)

str

In [22]:
#plot_df.to_dict('records')

In [23]:
#app.layout = table3
limits_df

,id,spin_dependency,result_type,measurement_type,nomhash,x_units,y_units,x_rescale,y_rescale,default_color,...,experiment,rating,date_of_announcement,public,official,date_official,greatest_hit,date_of_run_start,date_of_run_end,year
0,1,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,,,LtR,...,Theory,0,2003-01-01,1,1,None,0,None,None,2003.0
1,2,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
2,3,SD,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
3,4,SD,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,1,1e-36,Grn,...,Theory,0,2005-01-01,1,1,None,0,None,None,2005.0
4,5,SI,Th,Dir,b'--- \nknikolic: false\n',GeV,cm^2,,,LtB,...,Theory,0,2003-01-01,1,1,None,0,None,None,2003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
950,1115,SD,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1,Blk,...,XENONnT,0,None,1,0,None,0,None,None,2020.0
951,1116,SI,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1e-36,Blk,...,CRESST,0,None,1,0,None,0,None,None,2019.0
952,1117,SD,Exp,Dir,b'--- \npauser: false\n',GeV,cm^2,1,1e-36,Blk,...,CRESST,0,None,1,0,None,0,None,None,2019.0
953,1118,SI,Personal,Dir,b'--- \nandreyalexandrov: false\n',GeV,cm^2,1,1,Blk,...,,0,None,0,0,None,0,None,None,2021.0
954,1119,SI,Personal,Dir,b'--- \nandreyalexandrov: false\n',GeV,cm^2,1,1,Blk,...,,0,None,0,0,None,0,None,None,2021.0

In [24]:
plot_df = limits_df.copy()
dc  = plot_df.columns
dc

Index(['id', 'spin_dependency', 'result_type', 'measurement_type', 'nomhash',
       'x_units', 'y_units', 'x_rescale', 'y_rescale', 'default_color',
       'default_style', 'data_values', 'data_label', 'file_name',
       'data_comment', 'data_reference', 'created_at', 'updated_at',
       'creator_id', 'experiment', 'rating', 'date_of_announcement', 'public',
       'official', 'date_official', 'greatest_hit', 'date_of_run_start',
       'date_of_run_end', 'year'],
      dtype='object')

In [25]:
plot_df = allid
#plot_df = oneid

app.layout = html.Div([
    dash_table.DataTable(
        id='datatable-row-ids',
        columns=[
            {'name': i, 'id': i, 'deletable': True} for i in plot_df.columns
            # omit the id column
            if i not in ['data_comment','spin_dependency', 'measurement_type', 'nomhash',
       'x_units', 'y_units', 'x_rescale', 'y_rescale', 'default_color',
       'default_style', 'data_values', 'file_name',
        'created_at', 'updated_at',
       'creator_id', 'rating', 'date_of_announcement', 'public',
       'official', 'date_official', 'greatest_hit', 'date_of_run_start',
       'date_of_run_end']
        ],
        data=plot_df.to_dict('records'),
        editable=False,
        filter_action="native",
        sort_action="native",
        sort_mode='multi',
        row_selectable='single',
        row_deletable=False,
        selected_rows=[],
        page_action='native',
        page_current= 0,
        page_size= 10,
        derived_virtual_selected_row_ids=[],
        selected_row_ids=[]
    ),
    html.Div(id='datatable-row-ids-container')
])



@app.callback(
    Output(component_id='datatable-row-ids-container', component_property='children'),
    Input('datatable-row-ids', 'derived_virtual_row_ids'),
    Input('datatable-row-ids', 'selected_row_ids'),
    Input('datatable-row-ids', 'active_cell'))
def update_graphs(row_ids, selected_row_ids, active_cell):
    # When the table is first rendered, `derived_virtual_data` and
    # `derived_virtual_selected_rows` will be `None`. This is due to an
    # idiosyncrasy in Dash (unsupplied properties are always None and Dash
    # calls the dependent callbacks when the component is first rendered).
    # So, if `rows` is `None`, then the component was just rendered
    # and its value will be the same as the component's dataframe.
    # Instead of setting `None` in here, you could also set
    # `derived_virtual_data=df.to_rows('dict')` when you initialize
    # the component.
    
    #derived_virtual_data=data_df.to_dict('records')
    
    #selected_id_set = set(selected_row_ids or [])
    
    #value_list = ["apple"]

    boolean_series = plot_df.id.isin(selected_row_ids)

    filtered_df = plot_df[boolean_series].copy()
    
    #plot_df[plot_df['id']==100]

    plot_data = datastring2dataframe(filtered_df[['data_values']]).copy()
    
    if row_ids is None:
        dff = plot_data
        # pandas Series works enough like a list for this to be OK
        #row_ids = filtered_df['id']
        row_ids = [0]
    else:
        #dff = data_df.loc[row_ids]
        dff = plot_data
    
    
    active_row_id = active_cell['row'] if active_cell else None
    
    #dc = filtered_df['data_comment'][0]
    
    #print(dc)
    
    fig = go.Figure(
    data=[go.Scatter(x=dff['x'], y=dff['y'])],
    layout=go.Layout(
        #title=go.layout.Title(text="A Figure Specified By A Graph Object")
        ##title=go.layout.Title(text='y')
        title=go.layout.Title(text=filtered_df['data_label'].iloc[0])
        ##df_test['Btime'].iloc[0]
    )
)
    
    fig.update_layout(
    xaxis_title=filtered_df['x_units'].iloc[0],
    yaxis_title=filtered_df['y_units'].iloc[0],
    legend_title="Legend Title",
    font=dict(
        family="Courier New, monospace",
        size=18,
        color="RebeccaPurple"
    )
)
    
    
    graph = html.Div(children=[dcc.Graph(figure=fig)])
    
    
    '''graph = html.Div(children=[dcc.Graph(
            #id=column + '--row-ids',
            figure={
                'data': [
                    {
                        'x': dff['x'],
                        'y': dff['y'],
                        'type': 'scatter'#,
                        #'marker': {'color': colors},
                    }
                ],
                'layout': {
                    'xaxis': {'automargin': True},
                    'yaxis': {
                        'automargin': True,
                        'title': 'y',
                    },
                    'height': 250,
                    'margin': {'t': 10, 'l': 10, 'r': 10},
                },
            },
        )])'''
        # check if column exists - user may have deleted it
        # If `column.deletable=False`, then you don't
        # need to do this check.
        #for column in ['pop', 'lifeExp', 'gdpPercap'] if column in dff
        #for column in ['data_values'] if column in dff
    
    return graph


@app.callback(
    Output(component_id='datatable-row-ids-container', component_property='children'),
    Input('datatable-row-ids', 'derived_virtual_row_ids'),
    Input('datatable-row-ids', 'selected_row_ids'),
    Input('datatable-row-ids', 'active_cell'))
def update_graphs(row_ids, selected_row_ids, active_cell):
    # When the table is first rendered, `derived_virtual_data` and
    # `derived_virtual_selected_rows` will be `None`. This is due to an
    # idiosyncrasy in Dash (unsupplied properties are always None and Dash
    # calls the dependent callbacks when the component is first rendered).
    # So, if `rows` is `None`, then the component was just rendered
    # and its value will be the same as the component's dataframe.
    # Instead of setting `None` in here, you could also set
    # `derived_virtual_data=df.to_rows('dict')` when you initialize
    # the component.
    
    #derived_virtual_data=data_df.to_dict('records')
    
    #selected_id_set = set(selected_row_ids or [])
    
    #value_list = ["apple"]

    boolean_series = plot_df.id.isin(selected_row_ids)

    filtered_df = plot_df[boolean_series].copy()
    
    #plot_df[plot_df['id']==100]

    plot_data = datastring2dataframe(filtered_df[['data_values']]).copy()
    
    '''if row_ids is None:
        dff = plot_data
        # pandas Series works enough like a list for this to be OK
        #row_ids = filtered_df['id']
        row_ids = [0]
    else:
        #dff = data_df.loc[row_ids]
        dff = plot_data.loc[row_ids]
    '''
    
    active_row_id = active_cell['row'] if active_cell else None
    
    #dc = filtered_df['data_comment'][0]
    
    fig = go.Figure(
    data=[go.Scatter(x=dff['x'], y=dff['y'])],
    layout=go.Layout(
        title=go.layout.Title(text="A Figure Specified By A Graph Object")
        ##title=go.layout.Title(text='y')
    )
)
    
    
    graph = html.Div(children=[dcc.Graph(figure=fig)])
    
    
    '''graph = html.Div(children=[dcc.Graph(
            #id=column + '--row-ids',
            figure={
                'data': [
                    {
                        'x': dff['x'],
                        'y': dff['y'],
                        'type': 'scatter'#,
                        #'marker': {'color': colors},
                    }
                ],
                'layout': {
                    'xaxis': {'automargin': True},
                    'yaxis': {
                        'automargin': True,
                        'title': 'y',
                    },
                    'height': 250,
                    'margin': {'t': 10, 'l': 10, 'r': 10},
                },
            },
        )])'''
        # check if column exists - user may have deleted it
        # If `column.deletable=False`, then you don't
        # need to do this check.
        #for column in ['pop', 'lifeExp', 'gdpPercap'] if column in dff
        #for column in ['data_values'] if column in dff
    
    return graph

In [26]:
app.run_server(debug=True,port=5051)

Dash app running on http://127.0.0.1:5051/