In [55]:
import dash
import dash_core_components as dcc
import dash_html_components as html

from dash import Dash, Input, Output, callback

from jupyter_dash import JupyterDash

import dash_bootstrap_components as dbc
COMPONENT_STYLE = "/assets/my_component.css"
external_stylesheets=[dbc.themes.BOOTSTRAP]

app = JupyterDash(__name__, external_stylesheets=external_stylesheets,
                  meta_tags=[{'name': 'viewport', 'content': 'width=device-width, initial-scale=1'}],
                 suppress_callback_exceptions=True)
# Create server variable with Flask server object for use with gunicorn
server = app.server

In [56]:
import pandas as pd

In [57]:
import xml.etree.ElementTree as ET
tree = ET.parse('example.xml')
root = tree.getroot()
#dv_find = root.findall('data-values')
#data = dv_find[0].text

In [58]:
def find_xml_text(root_in,tag_in):
    dv_find = root_in.findall(tag_in)
    return dv_find[0].text

In [59]:
data_values = find_xml_text(root,'data-values')
data_comment = find_xml_text(root,'data-comment')

In [60]:
data_label = find_xml_text(root,'data-label')
data_reference = find_xml_text(root,'data-reference')
date_of_announcement = find_xml_text(root,'date-of-announcement')
date_of_run_end = find_xml_text(root,'date-of-run-end')
date_of_run_start = find_xml_text(root,'date-of-run-start')
default_color = find_xml_text(root,'default-color')

default_style = find_xml_text(root,'default-style')
experiment = find_xml_text(root,'experiment')
public = find_xml_text(root,'public')
result_type = find_xml_text(root,'result-type')
spin_dependency = find_xml_text(root,'spin-dependency')
x_rescale = find_xml_text(root,'x-rescale')
x_units = find_xml_text(root,'x-units')
y_rescale = find_xml_text(root,'y-rescale')
y_units = find_xml_text(root,'y-units')
year = find_xml_text(root,'year')

In [61]:
#data_df = []
data_record = [[data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,
               date_of_run_start,default_color,default_style,experiment,
               public,result_type,spin_dependency,x_rescale,x_units,y_rescale,
               y_units,year
              ]]
data_df = pd.DataFrame.from_records(data=data_record, columns = ['data_values','data_comment','data_label','data_reference','date_of_announcement','date_of_run_end',
               'date_of_run_start','default_color','default_style','experiment',
               'public','result_type','spin_dependency','x_rescale','x_units','y_rescale',
               'y_units','year'])
data_df

#data_df['id'] = df['country']
#df.set_index('id', inplace=True, drop=False)
data_df.index.name = 'id'
data_df['id'] = data_df.index
data_df

,data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,date_of_run_start,default_color,default_style,experiment,public,result_type,spin_dependency,x_rescale,x_units,y_rescale,y_units,year,id
id,,,,,,,,,,,,,,,,,,,
0,{[98.69386 2.679186e-08;117.6216 2.626349e-08;...,Markov chain monte carlo contours in CMSSM.,"Trotta et. al., 2008, CMSSM Bayesian: 68% cont...",arXiv:0809.3792,2008-01-01,None,None,DkB,Fill,Theory,true,Th,SI,1,GeV,1e-36,cm^2,2008,0

#string_data = ET.tostring(data, encoding="unicode")
#string_data
#data


data = data.replace("{[", "")
data = data.replace("]}", "")
x = data.split(";")
lol = []
for i in x:
    z = i.split(" ");
    appendthis = [z[0],z[1]]
    lol.append(appendthis)
#lol
df_experiment = pd.DataFrame(data=lol,columns=['raw_x','raw_y'])

df_experiment['x'] = df_experiment['raw_x'].astype(str).astype(float)
df_experiment['y'] = df_experiment['raw_y'].astype(str).astype(float)

df_experiment.dtypes

df_experiment.plot.scatter(x='x',y='y')

In [62]:
#https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/

#x range (WIMP mass) 	lower bound: 	to 	upper bound: 	GeV/c^2
#y range (cross-section) 	smallest c-s: 10^ 	to 	largest c-s: 10^ 	
#Table
#Result	Reference	Plot appearance

ResultTypeDropdown = dcc.Dropdown(
        id='resulttype-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'Experiment', 'value': 'Experiment'},
            {'label': 'Projection', 'value': 'Projection'},
            {'label': 'Theory', 'value': 'Theory'},
            {'label': 'Other', 'value': 'Other'},
            {'label': 'Personal', 'value': 'Personal'}            
        ],
        value='All'
    )

#dbc.DropdownMenu(
#    label="Menu",
#    children=[
#        dbc.DropdownMenuItem("Item 1"),
#        dbc.DropdownMenuItem("Item 2"),
#        dbc.DropdownMenuItem("Item 3"),
#    ],
#)

SpinDropdown = dcc.Dropdown(
        id='spin-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'spin-dependent', 'value': 'spin-dependent'},
            {'label': 'spin-indpendent', 'value': 'spin-indpendent'}    
        ],
        value='All'
    )


ExperimentDropdown = dcc.Dropdown(
        id='experiment-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'CDEX-10', 'value': ''},
            {'label': 'CDMS I (SUF)', 'value': ''},
            {'label': 'CDMS II (Soudan)', 'value': ''},
            {'label': 'CDMS II (Soudan)', 'value': ''},
            {'label': 'COSME', 'value': ''},
            {'label': 'COUPP', 'value': ''},
            {'label': 'COURICIONO', 'value': ''},
            {'label': 'CoGeNT', 'value': ''},
            {'label': 'Cuore', 'value': ''}
        ],
        value='All'
    )

YearDropdown = dcc.Dropdown(
        id='year-dropdown',
        options=[
            {'label': '2000', 'value': '2000'},
            {'label': '2001', 'value': '2001'},
            {'label': '2002', 'value': '2002'},
            {'label': '2003', 'value': '2003'},
            {'label': '2004', 'value': '2004'},
            {'label': '2005', 'value': '2005'},
            {'label': '2006', 'value': '2006'},
            {'label': '2007', 'value': '2007'},
            {'label': '2008', 'value': '2008'},
            {'label': '2009', 'value': '2009'},
            {'label': '2010', 'value': '2010'},
            {'label': '2011', 'value': '2011'},
            {'label': '2012', 'value': '2012'},
            {'label': '2013', 'value': '2013'},
            {'label': '2014', 'value': '2014'},
            {'label': '2015', 'value': '2015'},
            {'label': '2016', 'value': '2016'},
            {'label': '2017', 'value': '2017'},
            {'label': '2018', 'value': '2018'},
            {'label': '2019', 'value': '2019'},
            {'label': '2020', 'value': '2020'}
        ],
        value='All'
    )

GreatestHitsDropdown = dcc.Dropdown(
        id='greatesthits-dropdown',
        options=[
            {'label': 'All', 'value': 'All'},
            {'label': 'Greatest Hits', 'value': 'Greatest Hits'}
        ],
        value='All'
    )

#List of Research Results

#Result	Reference

In [63]:
import dash_bootstrap_components as dbc

form = dbc.Container(
    children=[dbc.Row(
    [
        dbc.Col(
            [
                dbc.Label("Result Type"),
                ResultTypeDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Spin"),
                SpinDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Experiment"),
                ExperimentDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Year"),
                YearDropdown,
            ],
            width=2,
        ),
        dbc.Col(
            [
                dbc.Label("Greatest Hits"),
                GreatestHitsDropdown,
            ],
            width=2,
        ),
    ],
    className="g-3",
)])

In [64]:
from dash import dash_table

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')

table1 = dash_table.DataTable(
    id='table',
    columns=[{"name": i, "id": i} for i in df.columns],
    data=df.to_dict('records'),
)

In [65]:
df = pd.read_csv('https://git.io/Juf1t')

table2 = dbc.Container([
    dbc.Label('Click a cell in the table:'),
    dash_table.DataTable(
        id='tbl', data=df.to_dict('records'),
        columns=[{"name": i, "id": i} for i in df.columns],
    ),
    dbc.Alert(id='tbl_out'),
])

@callback(Output('tbl_out', 'children'), Input('tbl', 'active_cell'))
def update_graphs(active_cell):
    return str(active_cell) if active_cell else "Click the table"

In [66]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/gapminder2007.csv')
# add an id column and set it as the index
# in this case the unique ID is just the country name, so we could have just
# renamed 'country' to 'id' (but given it the display name 'country'), but
# here it's duplicated just to show the more general pattern.
df['id'] = df['country']
df.set_index('id', inplace=True, drop=False)
df

,country,pop,continent,lifeExp,gdpPercap,id
id,,,,,,
Afghanistan,Afghanistan,31889923.0,Asia,43.828,974.580338,Afghanistan
Albania,Albania,3600523.0,Europe,76.423,5937.029526,Albania
Algeria,Algeria,33333216.0,Africa,72.301,6223.367465,Algeria
Angola,Angola,12420476.0,Africa,42.731,4797.231267,Angola
Argentina,Argentina,40301927.0,Americas,75.320,12779.379640,Argentina
...,...,...,...,...,...,...
Vietnam,Vietnam,85262356.0,Asia,74.249,2441.576404,Vietnam
West Bank and Gaza,West Bank and Gaza,4018332.0,Asia,73.422,3025.349798,West Bank and Gaza
"Yemen, Rep.","Yemen, Rep.",22211743.0,Asia,62.698,2280.769906,"Yemen, Rep."
Zambia,Zambia,11746035.0,Africa,42.384,1271.211593,Zambia
Zimbabwe,Zimbabwe,12311143.0,Africa,43.487,469.709298,Zimbabwe

layout_1 = html.Div([
    dash_table.DataTable(
        id='datatable-row-ids',
        columns=[
            {'name': i, 'id': i, 'deletable': True} for i in df.columns
            # omit the id column
            if i != 'id'
        ],
        data=df.to_dict('records'),
        editable=False,
        filter_action="native",
        sort_action="native",
        sort_mode='multi',
        row_selectable='single',
        row_deletable=False,
        selected_rows=[],
        page_action='native',
        page_current= 0,
        page_size= 10,
    ),
    html.Div(id='datatable-row-ids-container')
])


@app.callback(
    Output('datatable-row-ids-container', 'children'),
    Input('datatable-row-ids', 'derived_virtual_row_ids'),
    Input('datatable-row-ids', 'selected_row_ids'),
    Input('datatable-row-ids', 'active_cell'))
def update_graphs(row_ids, selected_row_ids, active_cell):
    # When the table is first rendered, `derived_virtual_data` and
    # `derived_virtual_selected_rows` will be `None`. This is due to an
    # idiosyncrasy in Dash (unsupplied properties are always None and Dash
    # calls the dependent callbacks when the component is first rendered).
    # So, if `rows` is `None`, then the component was just rendered
    # and its value will be the same as the component's dataframe.
    # Instead of setting `None` in here, you could also set
    # `derived_virtual_data=df.to_rows('dict')` when you initialize
    # the component.
    selected_id_set = set(selected_row_ids or [])

    if row_ids is None:
        dff = df
        # pandas Series works enough like a list for this to be OK
        row_ids = df['id']
    else:
        dff = df.loc[row_ids]

    active_row_id = active_cell['row_id'] if active_cell else None

    colors = ['#FF69B4' if id == active_row_id
              else '#7FDBFF' if id in selected_id_set
              else '#0074D9'
              for id in row_ids]

    return [
        dcc.Graph(
            id=column + '--row-ids',
            figure={
                'data': [
                    {
                        'x': dff['country'],
                        'y': dff[column],
                        'type': 'bar',
                        'marker': {'color': colors},
                    }
                ],
                'layout': {
                    'xaxis': {'automargin': True},
                    'yaxis': {
                        'automargin': True,
                        'title': {'text': column}
                    },
                    'height': 250,
                    'margin': {'t': 10, 'l': 10, 'r': 10},
                },
            },
        )
        # check if column exists - user may have deleted it
        # If `column.deletable=False`, then you don't
        # need to do this check.
        #for column in ['pop', 'lifeExp', 'gdpPercap'] if column in dff
        for column in ['pop'] if column in dff
    ]

In [67]:
def datastring2dataframe(data_values_in):
    data_list = data_values_in['data_values'].tolist()
    data_string = data_list[0]
    data_string = data_string.replace("{[", "")
    data_string = data_string.replace("]}", "")
    x = data_string.split(";")
    lol = []
    for i in x:
        z = i.split(" ");
        appendthis = [z[0],z[1]]
        lol.append(appendthis)
    #lol
    df_experiment = pd.DataFrame(data=lol,columns=['raw_x','raw_y'])

    df_experiment['x'] = df_experiment['raw_x'].astype(str).astype(float)
    df_experiment['y'] = df_experiment['raw_y'].astype(str).astype(float)

    #df_experiment.dtypes
    return df_experiment

In [68]:
data_df

,data_values,data_comment,data_label,data_reference,date_of_announcement,date_of_run_end,date_of_run_start,default_color,default_style,experiment,public,result_type,spin_dependency,x_rescale,x_units,y_rescale,y_units,year,id
id,,,,,,,,,,,,,,,,,,,
0,{[98.69386 2.679186e-08;117.6216 2.626349e-08;...,Markov chain monte carlo contours in CMSSM.,"Trotta et. al., 2008, CMSSM Bayesian: 68% cont...",arXiv:0809.3792,2008-01-01,None,None,DkB,Fill,Theory,true,Th,SI,1,GeV,1e-36,cm^2,2008,0

In [69]:
dict_ex = datastring2dataframe(data_df[['data_values']]).to_dict('records')
#dict_ex = df_ex.to_dict('records')
dict_ex
##data_list = data_df['data_values'].tolist()
##data_list[0]

[{'raw_x': '98.69386',
  'raw_y': '2.679186e-08',
  'x': 98.69386,
  'y': 2.679186e-08},
 {'raw_x': '117.6216',
  'raw_y': '2.626349e-08',
  'x': 117.6216,
  'y': 2.626349e-08},
 {'raw_x': '136.5493',
  'raw_y': '2.651613e-08',
  'x': 136.5493,
  'y': 2.651613e-08},
 {'raw_x': '155.4771',
  'raw_y': '2.834595e-08',
  'x': 155.4771,
  'y': 2.834595e-08},
 {'raw_x': '157.0919',
  'raw_y': '2.854799e-08',
  'x': 157.0919,
  'y': 2.854799e-08},
 {'raw_x': '174.4048',
  'raw_y': '3.407159e-08',
  'x': 174.4048,
  'y': 3.407159e-08},
 {'raw_x': '193.3326',
  'raw_y': '3.32569e-08',
  'x': 193.3326,
  'y': 3.32569e-08},
 {'raw_x': '212.2603',
  'raw_y': '3.007852e-08',
  'x': 212.2603,
  'y': 3.007852e-08},
 {'raw_x': '225.4428',
  'raw_y': '2.854799e-08',
  'x': 225.4428,
  'y': 2.854799e-08},
 {'raw_x': '231.1881',
  'raw_y': '2.813288e-08',
  'x': 231.1881,
  'y': 2.813288e-08},
 {'raw_x': '250.1158',
  'raw_y': '2.750528e-08',
  'x': 250.1158,
  'y': 2.750528e-08},
 {'raw_x': '269.0435',
  'raw_y': '2.72294e-08',
  'x': 269.0435,
  'y': 2.72294e-08},
 {'raw_x': '287.9713',
  'raw_y': '2.725936e-08',
  'x': 287.9713,
  'y': 2.725936e-08},
 {'raw_x': '306.899',
  'raw_y': '2.722701e-08',
  'x': 306.899,
  'y': 2.722701e-08},
 {'raw_x': '325.8268',
  'raw_y': '2.687628e-08',
  'x': 325.8268,
  'y': 2.687628e-08},
 {'raw_x': '344.7545',
  'raw_y': '2.657507e-08',
  'x': 344.7545,
  'y': 2.657507e-08},
 {'raw_x': '363.6823',
  'raw_y': '2.661759e-08',
  'x': 363.6823,
  'y': 2.661759e-08},
 {'raw_x': '382.61', 'raw_y': '2.632866e-08', 'x': 382.61, 'y': 2.632866e-08},
 {'raw_x': '401.5378',
  'raw_y': '2.575909e-08',
  'x': 401.5378,
  'y': 2.575909e-08},
 {'raw_x': '420.4655',
  'raw_y': '2.51039e-08',
  'x': 420.4655,
  'y': 2.51039e-08},
 {'raw_x': '439.3933',
  'raw_y': '2.423126e-08',
  'x': 439.3933,
  'y': 2.423126e-08},
 {'raw_x': '457.4588',
  'raw_y': '2.344148e-08',
  'x': 457.4588,
  'y': 2.344148e-08},
 {'raw_x': '458.321',
  'raw_y': '2.341474e-08',
  'x': 458.321,
  'y': 2.341474e-08},
 {'raw_x': '477.2487',
  'raw_y': '2.263085e-08',
  'x': 477.2487,
  'y': 2.263085e-08},
 {'raw_x': '496.1765',
  'raw_y': '2.142008e-08',
  'x': 496.1765,
  'y': 2.142008e-08},
 {'raw_x': '515.1042',
  'raw_y': '2.001227e-08',
  'x': 515.1042,
  'y': 2.001227e-08},
 {'raw_x': '525.1318',
  'raw_y': '1.92484e-08',
  'x': 525.1318,
  'y': 1.92484e-08},
 {'raw_x': '515.4892',
  'raw_y': '1.580534e-08',
  'x': 515.4892,
  'y': 1.580534e-08},
 {'raw_x': '515.1042',
  'raw_y': '1.578344e-08',
  'x': 515.1042,
  'y': 1.578344e-08},
 {'raw_x': '496.1765',
  'raw_y': '1.439755e-08',
  'x': 496.1765,
  'y': 1.439755e-08},
 {'raw_x': '477.2487',
  'raw_y': '1.320591e-08',
  'x': 477.2487,
  'y': 1.320591e-08},
 {'raw_x': '472.9571',
  'raw_y': '1.297817e-08',
  'x': 472.9571,
  'y': 1.297817e-08},
 {'raw_x': '458.321',
  'raw_y': '1.210741e-08',
  'x': 458.321,
  'y': 1.210741e-08},
 {'raw_x': '439.3933',
  'raw_y': '1.143267e-08',
  'x': 439.3933,
  'y': 1.143267e-08},
 {'raw_x': '420.4655',
  'raw_y': '1.110726e-08',
  'x': 420.4655,
  'y': 1.110726e-08},
 {'raw_x': '401.5378',
  'raw_y': '1.078924e-08',
  'x': 401.5378,
  'y': 1.078924e-08},
 {'raw_x': '396.3005',
  'raw_y': '1.065671e-08',
  'x': 396.3005,
  'y': 1.065671e-08},
 {'raw_x': '382.61', 'raw_y': '9.886143e-09', 'x': 382.61, 'y': 9.886143e-09},
 {'raw_x': '363.6823',
  'raw_y': '9.027664e-09',
  'x': 363.6823,
  'y': 9.027664e-09},
 {'raw_x': '356.2223',
  'raw_y': '8.750499e-09',
  'x': 356.2223,
  'y': 8.750499e-09},
 {'raw_x': '347.7909',
  'raw_y': '7.185259e-09',
  'x': 347.7909,
  'y': 7.185259e-09},
 {'raw_x': '344.981',
  'raw_y': '5.900001e-09',
  'x': 344.981,
  'y': 5.900001e-09},
 {'raw_x': '344.7545',
  'raw_y': '5.866719e-09',
  'x': 344.7545,
  'y': 5.866719e-09},
 {'raw_x': '331.4239',
  'raw_y': '4.844632e-09',
  'x': 331.4239,
  'y': 4.844632e-09},
 {'raw_x': '331.6817',
  'raw_y': '3.978052e-09',
  'x': 331.6817,
  'y': 3.978052e-09},
 {'raw_x': '338.5185',
  'raw_y': '3.26648e-09',
  'x': 338.5185,
  'y': 3.26648e-09},
 {'raw_x': '344.7545',
  'raw_y': '2.971179e-09',
  'x': 344.7545,
  'y': 2.971179e-09},
 {'raw_x': '349.3451',
  'raw_y': '2.682191e-09',
  'x': 349.3451,
  'y': 2.682191e-09},
 {'raw_x': '359.4349',
  'raw_y': '2.202416e-09',
  'x': 359.4349,
  'y': 2.202416e-09},
 {'raw_x': '363.6823',
  'raw_y': '2.044831e-09',
  'x': 363.6823,
  'y': 2.044831e-09},
 {'raw_x': '371.9502',
  'raw_y': '1.80846e-09',
  'x': 371.9502,
  'y': 1.80846e-09},
 {'raw_x': '382.61', 'raw_y': '1.594695e-09', 'x': 382.61, 'y': 1.594695e-09},
 {'raw_x': '389.9063',
  'raw_y': '1.484973e-09',
  'x': 389.9063,
  'y': 1.484973e-09},
 {'raw_x': '401.5378',
  'raw_y': '1.317298e-09',
  'x': 401.5378,
  'y': 1.317298e-09},
 {'raw_x': '406.3808',
  'raw_y': '1.21935e-09',
  'x': 406.3808,
  'y': 1.21935e-09},
 {'raw_x': '420.4655',
  'raw_y': '1.001504e-09',
  'x': 420.4655,
  'y': 1.001504e-09},
 {'raw_x': '420.4836',
  'raw_y': '1.001239e-09',
  'x': 420.4836,
  'y': 1.001239e-09},
 {'raw_x': '430.4575',
  'raw_y': '8.221433e-10',
  'x': 430.4575,
  'y': 8.221433e-10},
 {'raw_x': '439.3933',
  'raw_y': '7.212166e-10',
  'x': 439.3933,
  'y': 7.212166e-10},
 {'raw_x': '445.3367',
  'raw_y': '6.75083e-10',
  'x': 445.3367,
  'y': 6.75083e-10},
 {'raw_x': '458.321', 'raw_y': '6.06192e-10', 'x': 458.321, 'y': 6.06192e-10},
 {'raw_x': '472.3105',
  'raw_y': '5.54328e-10',
  'x': 472.3105,
  'y': 5.54328e-10},
 {'raw_x': '477.2487',
  'raw_y': '5.331807e-10',
  'x': 477.2487,
  'y': 5.331807e-10},
 {'raw_x': '494.1147',
  'raw_y': '4.551729e-10',
  'x': 494.1147,
  'y': 4.551729e-10},
 {'raw_x': '496.1765',
  'raw_y': '4.422628e-10',
  'x': 496.1765,
  'y': 4.422628e-10},
 {'raw_x': '506.1831',
  'raw_y': '3.737534e-10',
  'x': 506.1831,
  'y': 3.737534e-10},
 {'raw_x': '515.1042',
  'raw_y': '3.417769e-10',
  'x': 515.1042,
  'y': 3.417769e-10},
 {'raw_x': '530.299',
  'raw_y': '3.068985e-10',
  'x': 530.299,
  'y': 3.068985e-10},
 {'raw_x': '534.032',
  'raw_y': '3.012918e-10',
  'x': 534.032,
  'y': 3.012918e-10},
 {'raw_x': '552.9597',
  'raw_y': '2.815781e-10',
  'x': 552.9597,
  'y': 2.815781e-10},
 {'raw_x': '568.1944',
  'raw_y': '2.520022e-10',
  'x': 568.1944,
  'y': 2.520022e-10},
 {'raw_x': '571.8875',
  'raw_y': '2.456031e-10',
  'x': 571.8875,
  'y': 2.456031e-10},
 {'raw_x': '590.8152',
  'raw_y': '2.162332e-10',
  'x': 590.8152,
  'y': 2.162332e-10},
 {'raw_x': '596.8085',
  'raw_y': '2.069255e-10',
  'x': 596.8085,
  'y': 2.069255e-10},
 {'raw_x': '609.743',
  'raw_y': '1.929602e-10',
  'x': 609.743,
  'y': 1.929602e-10},
 {'raw_x': '628.4194',
  'raw_y': '1.699118e-10',
  'x': 628.4194,
  'y': 1.699118e-10},
 {'raw_x': '628.6707',
  'raw_y': '1.697132e-10',
  'x': 628.6707,
  'y': 1.697132e-10},
 {'raw_x': '647.5984',
  'raw_y': '1.614914e-10',
  'x': 647.5984,
  'y': 1.614914e-10},
 {'raw_x': '666.5262',
  'raw_y': '1.548291e-10',
  'x': 666.5262,
  'y': 1.548291e-10},
 {'raw_x': '685.4539', 'raw_y': '1.4314e-10', 'x': 685.4539, 'y': 1.4314e-10},
 {'raw_x': '691.8465',
  'raw_y': '1.39519e-10',
  'x': 691.8465,
  'y': 1.39519e-10},
 {'raw_x': '704.3817',
  'raw_y': '1.353513e-10',
  'x': 704.3817,
  'y': 1.353513e-10},
 {'raw_x': '723.3094',
  'raw_y': '1.331629e-10',
  'x': 723.3094,
  'y': 1.331629e-10},
 {'raw_x': '742.2372',
  'raw_y': '1.312313e-10',
  'x': 742.2372,
  'y': 1.312313e-10},
 {'raw_x': '761.1649',
  'raw_y': '1.25417e-10',
  'x': 761.1649,
  'y': 1.25417e-10},
 {'raw_x': '780.0927',
  'raw_y': '1.182032e-10',
  'x': 780.0927,
  'y': 1.182032e-10},
 {'raw_x': '787.6449',
  'raw_y': '1.145626e-10',
  'x': 787.6449,
  'y': 1.145626e-10},
 {'raw_x': '799.0204',
  'raw_y': '1.069114e-10',
  'x': 799.0204,
  'y': 1.069114e-10},
 {'raw_x': '810.7725',
  'raw_y': '9.40701e-11',
  'x': 810.7725,
  'y': 9.40701e-11},
 {'raw_x': '810.4317',
  'raw_y': '7.724339e-11',
  'x': 810.4317,
  'y': 7.724339e-11},
 {'raw_x': '799.0204',
  'raw_y': '6.55525e-11',
  'x': 799.0204,
  'y': 6.55525e-11},
 {'raw_x': '796.9614',
  'raw_y': '6.342652e-11',
  'x': 796.9614,
  'y': 6.342652e-11},
 {'raw_x': '780.0927',
  'raw_y': '5.60472e-11',
  'x': 780.0927,
  'y': 5.60472e-11},
 {'raw_x': '766.1689',
  'raw_y': '5.208114e-11',
  'x': 766.1689,
  'y': 5.208114e-11},
 {'raw_x': '761.1649',
  'raw_y': '5.095844e-11',
  'x': 761.1649,
  'y': 5.095844e-11},
 {'raw_x': '742.2372',
  'raw_y': '4.820796e-11',
  'x': 742.2372,
  'y': 4.820796e-11},
 {'raw_x': '723.3094',
  'raw_y': '4.707768e-11',
  'x': 723.3094,
  'y': 4.707768e-11},
 {'raw_x': '704.3817',
  'raw_y': '4.710802e-11',
  'x': 704.3817,
  'y': 4.710802e-11},
 {'raw_x': '685.4539',
  'raw_y': '4.794049e-11',
  'x': 685.4539,
  'y': 4.794049e-11},
 {'raw_x': '666.5262',
  'raw_y': '4.87192e-11',
  'x': 666.5262,
  'y': 4.87192e-11},
 {'raw_x': '647.5984',
  'raw_y': '4.966398e-11',
  'x': 647.5984,
  'y': 4.966398e-11},
 {'raw_x': '628.6707',
  'raw_y': '5.18708e-11',
  'x': 628.6707,
  'y': 5.18708e-11},
 {'raw_x': '627.6828',
  'raw_y': '5.208114e-11',
  'x': 627.6828,
  'y': 5.208114e-11},
 {'raw_x': '609.743',
  'raw_y': '5.662914e-11',
  'x': 609.743,
  'y': 5.662914e-11},
 {'raw_x': '595.6129',
  'raw_y': '6.342652e-11',
  'x': 595.6129,
  'y': 6.342652e-11},
 {'raw_x': '590.8152',
  'raw_y': '6.663166e-11',
  'x': 590.8152,
  'y': 6.663166e-11},
 {'raw_x': '576.6853',
  'raw_y': '7.724339e-11',
  'x': 576.6853,
  'y': 7.724339e-11},
 {'raw_x': '571.8875',
  'raw_y': '8.066095e-11',
  'x': 571.8875,
  'y': 8.066095e-11},
 {'raw_x': '552.9597',
  'raw_y': '9.214178e-11',
  'x': 552.9597,
  'y': 9.214178e-11},
 {'raw_x': '550.2962',
  'raw_y': '9.40701e-11',
  'x': 550.2962,
  'y': 9.40701e-11},
 {'raw_x': '534.032',
  'raw_y': '1.046451e-10',
  'x': 534.032,
  'y': 1.046451e-10},
 {'raw_x': '524.3892',
  'raw_y': '1.145626e-10',
  'x': 524.3892,
  'y': 1.145626e-10},
 {'raw_x': '515.1042',
  'raw_y': '1.236538e-10',
  'x': 515.1042,
  'y': 1.236538e-10},
 {'raw_x': '498.7524',
  'raw_y': '1.39519e-10',
  'x': 498.7524,
  'y': 1.39519e-10},
 {'raw_x': '496.1765',
  'raw_y': '1.418581e-10',
  'x': 496.1765,
  'y': 1.418581e-10},
 {'raw_x': '477.2487',
  'raw_y': '1.588487e-10',
  'x': 477.2487,
  'y': 1.588487e-10},
 {'raw_x': '467.8352',
  'raw_y': '1.699118e-10',
  'x': 467.8352,
  'y': 1.699118e-10},
 {'raw_x': '458.321',
  'raw_y': '1.826223e-10',
  'x': 458.321,
  'y': 1.826223e-10},
 {'raw_x': '444.2626',
  'raw_y': '2.069255e-10',
  'x': 444.2626,
  'y': 2.069255e-10},
 {'raw_x': '439.3933',
  'raw_y': '2.192908e-10',
  'x': 439.3933,
  'y': 2.192908e-10},
 {'raw_x': '428.3659',
  'raw_y': '2.520022e-10',
  'x': 428.3659,
  'y': 2.520022e-10},
 {'raw_x': '420.4655',
  'raw_y': '2.759709e-10',
  'x': 420.4655,
  'y': 2.759709e-10},
 {'raw_x': '410.5131',
  'raw_y': '3.068985e-10',
  'x': 410.5131,
  'y': 3.068985e-10},
 {'raw_x': '401.5378',
  'raw_y': '3.368937e-10',
  'x': 401.5378,
  'y': 3.368937e-10},
 {'raw_x': '390.1735',
  'raw_y': '3.737534e-10',
  'x': 390.1735,
  'y': 3.737534e-10},
 {'raw_x': '382.61', 'raw_y': '3.974625e-10', 'x': 382.61, 'y': 3.974625e-10},
 {'raw_x': '367.3452',
  'raw_y': '4.551729e-10',
  'x': 367.3452,
  'y': 4.551729e-10},
 {'raw_x': '363.6823',
  'raw_y': '4.708131e-10',
  'x': 363.6823,
  'y': 4.708131e-10},
 {'raw_x': '349.7902',
  'raw_y': '5.54328e-10',
  'x': 349.7902,
  'y': 5.54328e-10},
 {'raw_x': '344.7545',
  'raw_y': '5.894607e-10',
  'x': 344.7545,
  'y': 5.894607e-10},
 {'raw_x': '334.5707',
  'raw_y': '6.75083e-10',
  'x': 334.5707,
  'y': 6.75083e-10},
 {'raw_x': '325.8268',
  'raw_y': '7.641786e-10',
  'x': 325.8268,
  'y': 7.641786e-10},
 {'raw_x': '320.1882',
  'raw_y': '8.221433e-10',
  'x': 320.1882,
  'y': 8.221433e-10},
 {'raw_x': '306.899',
  'raw_y': '1.001071e-09',
  'x': 306.899,
  'y': 1.001071e-09},
 {'raw_x': '306.8861',
  'raw_y': '1.001239e-09',
  'x': 306.8861,
  'y': 1.001239e-09},
 {'raw_x': '295.2839',
  'raw_y': '1.21935e-09',
  'x': 295.2839,
  'y': 1.21935e-09},
 {'raw_x': '287.9713',
  'raw_y': '1.402541e-09',
  'x': 287.9713,
  'y': 1.402541e-09},
 {'raw_x': '284.7714',
  'raw_y': '1.484973e-09',
  'x': 284.7714,
  'y': 1.484973e-09},
 {'raw_x': '271.6825',
  'raw_y': '1.80846e-09',
  'x': 271.6825,
  'y': 1.80846e-09},
 {'raw_x': '269.0435',
  'raw_y': '1.865525e-09',
  'x': 269.0435,
  'y': 1.865525e-09},
 {'raw_x': '260.1539',
  'raw_y': '2.202416e-09',
  'x': 260.1539,
  'y': 2.202416e-09},
 {'raw_x': '254.1953',
  'raw_y': '2.682191e-09',
  'x': 254.1953,
  'y': 2.682191e-09},
 {'raw_x': '250.1158',
  'raw_y': '3.126877e-09',
  'x': 250.1158,
  'y': 3.126877e-09},
 {'raw_x': '248.6352',
  'raw_y': '3.26648e-09',
  'x': 248.6352,
  'y': 3.26648e-09},
 {'raw_x': '241.0266',
  'raw_y': '3.978052e-09',
  'x': 241.0266,
  'y': 3.978052e-09},
 {'raw_x': '234.8194',
  'raw_y': '4.844632e-09',
  'x': 234.8194,
  'y': 4.844632e-09},
 {'raw_x': '231.1881',
  'raw_y': '4.991309e-09',
  'x': 231.1881,
  'y': 4.991309e-09},
 {'raw_x': '212.2603',
  'raw_y': '5.84087e-09',
  'x': 212.2603,
  'y': 5.84087e-09},
 {'raw_x': '211.4888',
  'raw_y': '5.900001e-09',
  'x': 211.4888,
  'y': 5.900001e-09},
 {'raw_x': '193.3326',
  'raw_y': '6.438254e-09',
  'x': 193.3326,
  'y': 6.438254e-09},
 {'raw_x': '183.5307',
  'raw_y': '7.185259e-09',
  'x': 183.5307,
  'y': 7.185259e-09},
 {'raw_x': '174.4048',
  'raw_y': '8.118192e-09',
  'x': 174.4048,
  'y': 8.118192e-09},
 {'raw_x': '169.1688',
  'raw_y': '8.750499e-09',
  'x': 169.1688,
  'y': 8.750499e-09},
 {'raw_x': '155.4771',
  'raw_y': '1.042688e-08',
  'x': 155.4771,
  'y': 1.042688e-08},
 {'raw_x': '150.7374',
  'raw_y': '1.065671e-08',
  'x': 150.7374,
  'y': 1.065671e-08},
 {'raw_x': '136.5493',
  'raw_y': '1.10223e-08',
  'x': 136.5493,
  'y': 1.10223e-08},
 {'raw_x': '117.6216',
  'raw_y': '1.157054e-08',
  'x': 117.6216,
  'y': 1.157054e-08},
 {'raw_x': '103.3434',
  'raw_y': '1.297817e-08',
  'x': 103.3434,
  'y': 1.297817e-08},
 {'raw_x': '98.69386',
  'raw_y': '1.385948e-08',
  'x': 98.69386,
  'y': 1.385948e-08},
 {'raw_x': '90.26887',
  'raw_y': '1.580534e-08',
  'x': 90.26887,
  'y': 1.580534e-08},
 {'raw_x': '86.91604',
  'raw_y': '1.92484e-08',
  'x': 86.91604,
  'y': 1.92484e-08},
 {'raw_x': '89.14968',
  'raw_y': '2.344148e-08',
  'x': 89.14968,
  'y': 2.344148e-08},
 {'raw_x': '98.69386',
  'raw_y': '2.679186e-08',
  'x': 98.69386,
  'y': 2.679186e-08}]

In [70]:
app.layout = html.Div([
    dash_table.DataTable(
        id='datatable-row-ids',
        columns=[
            {'name': i, 'id': i, 'deletable': True} for i in data_df.columns
            # omit the id column
            if i not in ['id','data_values','data_reference',
                         'date_of_announcement','date_of_run_end',
                         'date_of_run_start','default_color','default_style']
        ],
        data=data_df.to_dict('records'),
        editable=False,
        filter_action="native",
        sort_action="native",
        sort_mode='multi',
        row_selectable='single',
        row_deletable=False,
        selected_rows=[],
        page_action='native',
        page_current= 0,
        page_size= 10,
        derived_virtual_selected_row_ids=[],
        selected_row_ids=[]
    ),
    html.Div(id='datatable-row-ids-container')
])


@app.callback(
    Output(component_id='datatable-row-ids-container', component_property='children'),
    Input('datatable-row-ids', 'derived_virtual_row_ids'),
    Input('datatable-row-ids', 'selected_row_ids'),
    Input('datatable-row-ids', 'active_cell'))
def update_graphs(row_ids, selected_row_ids, active_cell):
    # When the table is first rendered, `derived_virtual_data` and
    # `derived_virtual_selected_rows` will be `None`. This is due to an
    # idiosyncrasy in Dash (unsupplied properties are always None and Dash
    # calls the dependent callbacks when the component is first rendered).
    # So, if `rows` is `None`, then the component was just rendered
    # and its value will be the same as the component's dataframe.
    # Instead of setting `None` in here, you could also set
    # `derived_virtual_data=df.to_rows('dict')` when you initialize
    # the component.
    
    #derived_virtual_data=data_df.to_dict('records')
    
    selected_id_set = set(selected_row_ids or [])

    plot_data = datastring2dataframe(data_df[['data_values']])
    
    if row_ids is None:
        dff = plot_data
        # pandas Series works enough like a list for this to be OK
        row_ids = data_df['id']
    else:
        #dff = data_df.loc[row_ids]
        dff = plot_data

    active_row_id = active_cell['row'] if active_cell else None

    return [
        dcc.Graph(
            #id=column + '--row-ids',
            figure={
                'data': [
                    {
                        'x': dff['x'],
                        'y': dff['y'],
                        'type': 'scatter'#,
                        #'marker': {'color': colors},
                    }
                ],
                'layout': {
                    'xaxis': {'automargin': True},
                    'yaxis': {
                        'automargin': True,
                        'title': {'text': 'y'}
                    },
                    'height': 250,
                    'margin': {'t': 10, 'l': 10, 'r': 10},
                },
            },
        )
        # check if column exists - user may have deleted it
        # If `column.deletable=False`, then you don't
        # need to do this check.
        #for column in ['pop', 'lifeExp', 'gdpPercap'] if column in dff
        #for column in ['data_values'] if column in dff
    ]

In [71]:
#app.layout = table3

In [72]:
app.run_server(debug=True,port=5051)

Dash app running on http://127.0.0.1:5051/

/home/andrewcgaitskell/.local/share/virtualenvs/dmtoolnotes-z4lOQ0W-/lib/python3.8/site-packages/jupyter_dash/jupyter_app.py:139: UserWarning:

The 'environ['werkzeug.server.shutdown']' function is deprecated and will be removed in Werkzeug 2.1.